network:
  version: 2
  renderer: networkd
  ethernets:
    enp5s0f1:
      match:
        macaddress: a0:42:3f:44:56:5b
      addresses:
      - 51.222.70.226/32
      gateway4: 51.222.70.254
      routes:
      - to: 51.222.70.254
        scope: link
